version: "3.8"

networks:
  hazelcast-network:


services:
  hazelcast_1:
    image: hazelcast/hazelcast:latest-snapshot-slim
    ports:
      - "5701:5701"
    environment:
      - HZ_NETWORK_PUBLICADDRESS=hazelcast_1:5701
    networks:
      - hazelcast-network

  hazelcast_2:
    image: hazelcast/hazelcast:latest-snapshot-slim
    ports:
      - "5702:5701"
    environment:
      - HZ_NETWORK_PUBLICADDRESS=hazelcast_2:5702
    networks:
      - hazelcast-network

  hazelcast_3:
    image: hazelcast/hazelcast:latest-snapshot-slim
    ports:
      - "5703:5701"
    environment:
      - HZ_NETWORK_PUBLICADDRESS=hazelcast_3:5703
    networks:
      - hazelcast-network
