version: "3.8"

networks:
  hazelcast-network:
    driver: bridge


services:
  hazelcast_1:
    image: hazelcast/hazelcast:latest-snapshot-slim
    ports:
      - "5701:5701"
    environment:
      - HZ_NETWORK_PUBLICADDRESS=localhost:5701
      - JAVA_OPTS=-Dhazelcast.yaml=/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - hazelcast-network

  hazelcast_2:
    image: hazelcast/hazelcast:latest-snapshot-slim
    ports:
      - "5702:5701"
    environment:
      - HZ_NETWORK_PUBLICADDRESS=localhost:5702
      - JAVA_OPTS=-Dhazelcast.yaml=/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - hazelcast-network

  hazelcast_3:
    image: hazelcast/hazelcast:latest-snapshot-slim
    ports:
      - "5703:5701"
    environment:
      - HZ_NETWORK_PUBLICADDRESS=localhost:5703
      - JAVA_OPTS=-Dhazelcast.yaml=/opt/hazelcast/config_ext/hazelcast.yaml
    networks:
      - hazelcast-network
